builds:
  - binary: siml 
    main: .
    ldflags:
      - -s -w
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64
  
archives:
  - id: zip
    format: zip
    replacements:
      darwin: macOS
